# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e419976c90b8e9ff4c82cebff511acce4c3525d64fa0af604015d2c458dcf52dc5c8761572ded9e13100d3afba40bc4cbbe61e7659d7e6debb0363c8f685375c

test:
  secret_key_base: 4d506321f6f5d8fdb18ec8aff17165250071d102846724efee1048a68e79eaaaeaa44481b07cce887652de3c40ead6b81b52acb8f196f1d092c3df9a0c70f051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
